version: '3.8'

services:
  userpersistenceapi:
    image: userpersistence:latest
    container_name: userpersistence_container
    ports:
      - "5201:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "HML"
    networks:
      - techchallengenetwork

networks:
  techchallengenetwork:
    external: true